[package]
name = "cairo_project"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.7.0"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.31.0" }
assert_macros = "0.1.0"

[scripts]
test = "snforge test"

[[target.starknet-contract]]
sierra = true
casm = false